Fix + and full work project crud
Dmitriy870/ToDo_core pull request #1
Opened 2024-12-28 21:16 UTC by Dmitriy870

2024-12-30 09:22 UTC, ArtsiomSt requested changes
Давай посмотрим в сторону https://docs.djangoproject.com/en/5.1/topics/class-based-views/mixins/ и вынесения всей логики работы с объектами в сериализаторы. В джанге не пишем service как в фастапи. Как пример подобного разбиения посмотри в репозитории который я скидывал

Еще да, согласен, давай все-таки вынесем serializers на уровень выше - в папку api

2024-12-30 09:22 UTC, ArtsiomSt commented on todocore/projects/api/service.py
> +from projects.models import Project, ProjectUser
Настрой плиз пре-коммиты, а то судя по порядку импортов они не настроены

2024-12-30 09:22 UTC, ArtsiomSt commented on todocore/projects/api/service.py
> +        return Project.objects.filter(**filters)
Увы но это не фастапи, давай тут без таких сервисов. Здесь в service.py выносим только бизнес логику. Если хочется эту логику выносить отдельно - то ее можно писать в сериализаторах. Если хочется иметь прямо класс по типу "репозитория", то туда выноси методы, которые выполняют более сложные операции, а то тут получается у нас куча методов однострочников. + Страйся типизировать все, несмотря на то что это джанга

2024-12-30 09:22 UTC, ArtsiomSt commented on todocore/projects/api/service.py
> +        return ProjectUser.objects.filter(project=project, user=user).delete()
Я бы хотел вынести эту логику в сериализаторы, чтобы это все вызывалось автоматически, глянь как раз в примере CarShowRooms. Я хочу чтобы ты переопредял методы create delete и тд в сериализаторах

2024-12-30 09:22 UTC, ArtsiomSt commented on todocore/projects/api/v1/serializers.py
> +        return data
А нам это надо если стоит required=True стоит?

2024-12-30 09:22 UTC, ArtsiomSt commented on todocore/projects/api/v1/serializers.py
> +    role = serializers.ChoiceField(choices=ProjectUser.ROLE_CHOICES, required=True)
Вот тут привязать ту логику описанную выше вот сюда

2024-12-30 09:22 UTC, ArtsiomSt commented on todocore/projects/api/v1/serializers.py
> +        fields = "__all__"
Кажется это можно объединить в один класс

2024-12-30 09:22 UTC, ArtsiomSt commented on todocore/projects/api/v1/urls.py
> +from .views import ProjectSearchViewSet, ProjectUserViewSet, ProjectViewSet
От относительных импоротов уходим, строим их от корня приложения

2024-12-30 09:22 UTC, ArtsiomSt commented on todocore/projects/api/v1/views.py
> +        raise ValidationError(serializer.errors)
Оно разве не будет автоматически вызывать create и update у сериализатора? я бы хотел чтобы вся такая логика была в них, как в примере CarShowRooms

2024-12-30 09:22 UTC, ArtsiomSt commented on todocore/projects/api/v1/views.py
> +        return Response(serializer.data)
Тоже мне кажется уже есть Mixins для этого, почитай про https://docs.djangoproject.com/en/5.1/topics/class-based-views/mixins/

2024-12-30 09:22 UTC, ArtsiomSt commented on todocore/projects/api/v1/views.py
> +            return Response({"error": e}, status=status.HTTP_400_BAD_REQUEST)
Надо всю логику из view выносить) вся логика создания объектов - в сериализаторах

2024-12-30 09:22 UTC, ArtsiomSt commented on todocore/projects/api/v1/views.py
> +        return Response({"message": "User removed from project"}, status=status.HTTP_204_NO_CONTENT)
Тоже хочу чтоб ты вынес эту логику в сериализатор)

2024-12-30 16:01 UTC, ArtsiomSt requested changes
С большего окей, давай ток как я писал все-таки вернем обратно serializers.py на уровень выше в api, те чтоб было api.seriazliers

2024-12-30 16:01 UTC, ArtsiomSt commented on todocore/projects/api/v1/serializers.py
> +        return instance
На 100 проц не уверен, но как будто эти методы не нужны, так как они = дефолтным. Поле created_by нельзя просто сделать обязательным чтоб джанга сама проверял?

2024-12-30 16:01 UTC, ArtsiomSt commented on todocore/projects/api/v1/serializers.py
> +            )
Тут мне тоже кажется лишнее, джанговский сериализатор сам не проверяет что переданная строка соотвествует указанному Enumу?

2024-12-30 16:01 UTC, ArtsiomSt commented on todocore/projects/api/v1/serializers.py
> +        role = data.get("role", "Reader")
Го сделаем дефолтным в сериализаторе, чтобы тут не писать

2024-12-30 16:01 UTC, ArtsiomSt commented on todocore/projects/api/v1/serializers.py
> +            )
Тут тоже если получится сделать так чтоб джанга сама проверяла, что значение соответсвует енаму

2024-12-30 16:01 UTC, ArtsiomSt commented on todocore/projects/api/v1/views.py
> +            user_id = self.request.data.get("user")
Не очень понял тут, типо если не передали в кваргах то берем из тела запроса? как будто это лишнее и для получения обязательно передать именно в кваграх

2024-12-30 18:53 UTC, Dmitriy870 commented on todocore/projects/api/v1/views.py
> +            user_id = self.request.data.get("user")
Убрал

2024-12-30 22:12 UTC, Dmitriy870 commented on todocore/projects/api/v1/serializers.py
> +            )
Все сама делает теперь

2024-12-30 22:14 UTC, Dmitriy870 commented on todocore/projects/api/v1/serializers.py
> +        return instance
update снес а create оставил,без него нет четкой ошибки что произошло

2024-12-30 22:20 UTC, Dmitriy870 commented on todocore/projects/api/v1/serializers.py
> +        role = data.get("role", "Reader")
не совсем понял
сделать просто дефорлное значение в сериализаторе?

2024-12-31 10:25 UTC, ArtsiomSt approved these changes

2024-12-31 10:25 UTC, ArtsiomSt commented on todocore/projects/api/serializers.py
> +        fields = "__all__"
А я правильно понимаю что в таком случае джанга дает возможность при отправки установить поля id created_at и updated_at? просто эти поля должны быть только авто-заполяемыми

2024-12-31 10:25 UTC, ArtsiomSt commented on todocore/projects/api/v1/serializers.py
> +        role = data.get("role", "Reader")
Угу

2024-12-31 10:25 UTC, ArtsiomSt commented on todocore/projects/api/v1/urls.py
> +from .views import ProjectUserViewSet, ProjectViewSet
относительный импорт)

2024-12-31 10:27 UTC, Dmitriy870 commented on todocore/projects/api/serializers.py
> +        fields = "__all__"
Не,не дает
они в самой модели автозаполняемые

2024-12-31 10:28 UTC, Dmitriy870 commented on todocore/projects/api/v1/urls.py
> +from .views import ProjectUserViewSet, ProjectViewSet
😞

2024-12-31 12:13 UTC, merged